# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack",
  "email": "jones23@overlook.net",
  "avatar": "",
  "password": "123456",
  "isPro": false
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "jones23@overlook.net",
  "password": "123"
}

###

## Отправить изображение

POST http://localhost:5000/users/6548c5f043927a226009bba6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
