# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack Jones 1",
  "email": "jackjones1@overlook.com",
  "avatar": "jackjones1.png",
  "password": "123456",
  "isPro": true,
  "favorites": []
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "jackjones1@overlook.com",
  "password": "123456"
}

###

## Отправить изображение

POST http://localhost:5000/users/6548c5f043927a226009bba6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="test.png"
Content-Type: image/png

< C:\test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvbmVzNDRAb3Zlcmxvb2submV0IiwibmFtZSI6IkphY2siLCJpZCI6IjY1NTA1Y2FhZGE5ZGUwOGRhOTc2OWRjNiIsImlhdCI6MTY5OTc2NTQzNSwiZXhwIjoxNjk5OTM4MjM1fQ.Z7C5jG5wC-VxJ1In-gKcCmJsnyWO9Ikf4snyRE1dbLM

##
