# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack Jones 55",
  "email": "jackjones55@overlook.com",
  "avatar": "jackjones55.png",
  "password": "123456",
  "isPro": true,
  "favorites": []
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "jackjones1@overlook.com",
  "password": "123456"
}

###

## Отправить изображение

POST http://localhost:5000/users/6548c5f043927a226009bba6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="test.png"
Content-Type: image/png

< C:\test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImphY2tqb25lczU1QG92ZXJsb29rLmNvbSIsIm5hbWUiOiJKYWNrIEpvbmVzIDU1IiwiaWQiOiI2NTUzY2ExOGY1ODgxZDcwNzZlOWYyOTgiLCJpYXQiOjE3MDAwMTk0MjYsImV4cCI6MTcwMDE5MjIyNn0.hCNSEMLIHuGDQSEc0SPGVZFwbYjGhD11qiW0Rnj0U4I

##
